// Generates src/content/directus.schema.ts (zod schemas) from Directus field metadata.
// Run after changing collections/fields in Directus:  pnpm directus:schema
//
// Mapping: required → strict, otherwise .nullable(); file-image → imageSchema; file → fileSchema;
// m2o → reference('<collection>'); list interface → z.array(z.object(...)) from options.fields;
// select-dropdown with static choices → z.enum([...]).

import { writeFile } from 'node:fs/promises';

process.loadEnvFile('.env');
const BASE = process.env.DIRECTUS_URL?.replace(/\/$/, '');
const TOKEN = process.env.DIRECTUS_TOKEN;
if (!BASE || !TOKEN) throw new Error('DIRECTUS_URL / DIRECTUS_TOKEN missing in .env');

const OUT = 'src/content/directus.schema.ts';

async function api(path) {
  const res = await fetch(`${BASE}${path}`, { headers: { Authorization: `Bearer ${TOKEN}` } });
  if (!res.ok) throw new Error(`${path} → ${res.status}`);
  return (await res.json()).data;
}

const [collections, fields, relations] = await Promise.all([
  api('/collections'),
  api('/fields'),
  api('/relations'),
]);

const userCollections = collections
  .filter((c) => !c.collection.startsWith('directus_') && c.schema) // skip folders
  .map((c) => c.collection)
  .sort();

const relatedOf = new Map(relations.map((r) => [`${r.collection}.${r.field}`, r.related_collection]));

const enumOf = (choices) =>
  Array.isArray(choices) && choices.length && choices.every((c) => typeof c.value === 'string')
    ? `z.enum([${choices.map((c) => JSON.stringify(c.value)).join(', ')}])`
    : null;

/** zod expression for a scalar/json field (without nullability). */
function zodFor(collection, f) {
  const meta = f.meta ?? {};
  const iface = meta.interface ?? '';
  const special = meta.special ?? [];
  const opts = meta.options ?? {};

  if (special.includes('file')) return iface === 'file-image' ? 'imageSchema' : 'fileSchema';
  if (special.includes('m2o')) {
    const related = relatedOf.get(`${collection}.${f.field}`);
    return related ? `reference(${JSON.stringify(related)})` : 'z.string()';
  }

  switch (f.type) {
    case 'string':
    case 'text':
    case 'uuid':
    case 'hash':
    case 'date':
    case 'dateTime':
    case 'timestamp':
    case 'time':
      return enumOf(opts.choices) ?? 'z.string()';
    case 'integer':
    case 'bigInteger':
    case 'float':
    case 'decimal':
      return 'z.number()';
    case 'boolean':
      return 'z.boolean()';
    case 'json': {
      if (iface === 'tags') return 'z.array(z.string())';
      if (iface === 'select-multiple-dropdown') return `z.array(${enumOf(opts.choices) ?? 'z.string()'})`;
      if (iface === 'list' && Array.isArray(opts.fields)) {
        // Sub-fields are strict only when marked required in the list options (rows may omit keys).
        const props = opts.fields.map(
          (sf) => `${ident(sf.field)}: ${zodFor(collection, sf)}${sf.meta?.required ? '' : '.nullish()'}`,
        );
        return `z.array(z.object({ ${props.join(', ')} }))`;
      }
      return 'z.unknown()';
    }
    default:
      return 'z.unknown()';
  }
}

const ident = (name) => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name));

const lines = [
  '// AUTO-GENERATED by scripts/directus-schema.mjs — do not edit by hand.',
  '// Regenerate after changing fields in Directus:  pnpm directus:schema',
  "import { reference } from 'astro:content';",
  "import { z } from 'astro/zod';",
  "import { fileSchema, imageSchema } from '@/lib/directus-loader';",
  '',
];

const singletons = [];
lines.push('export const schemas = {');
for (const collection of userCollections) {
  const meta = collections.find((c) => c.collection === collection).meta ?? {};
  if (meta.singleton) singletons.push(collection);

  const own = fields
    .filter((f) => f.collection === collection)
    .filter((f) => !(f.meta?.special ?? []).includes('no-data') && f.type !== 'alias')
    .sort((a, b) => (a.meta?.sort ?? 0) - (b.meta?.sort ?? 0));

  lines.push(`  ${collection}: z.object({`);
  for (const f of own) {
    const isPk = f.schema?.is_primary_key;
    let expr = isPk ? (f.type === 'integer' ? 'z.number()' : 'z.string()') : zodFor(collection, f);
    if (!isPk && !f.meta?.required) expr += '.nullable()';
    lines.push(`    ${ident(f.field)}: ${expr},`);
  }
  lines.push('  }),', '');
}
lines.push('};', '');

lines.push(`/** Collections configured as singletons in Directus. */`);
lines.push(`export const singletons = ${JSON.stringify(singletons)} as const;`, '');

await writeFile(OUT, lines.join('\n') + '\n');
console.log(`wrote ${OUT}: ${userCollections.length} collections (${singletons.length} singletons)`);
